var a = 6;
var b = 3;
document.write("a:" + a + ", b: " + b);
c = a + b;
document.write("<br>addition is: " + c);
d = a - b;
document.write("<br>sub is: " + d);
e = a * b;
document.write("<br>* is: " + e);
f = a / b;
document.write("<br>/ is: " + f);
g = a % b;
document.write("<br>% is: " + g);
h = a ** b;
document.write("<br>**(6^3): " + h);
a++;
document.write("<br>a++ is: " + a);
b--;
document.write("<br>b-- is: " + b);
